blank_issues_enabled: true
contact_links:
  - name: Installation Help
    url: https://discord.convoypanel.com
    about: Please visit our Discord for help with your installation.
  - name: General Question
    url: https://discord.convoypanel.com
    about: Please visit our Discord for general questions about Pterodactyl.
  - name: Documentation
    url: https://docs.convoypanel.com
    about: Our documentation may have an answer for your issue/question.